name: Deploy to AWS S3 + CloudFront

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Sync files to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} \
            --exclude ".git/*" \
            --exclude "node_modules/*" \
            --exclude ".github/*" \
            --exclude "*.md" \
            --exclude ".DS_Store" \
            --exclude "deploy.sh" \
            --delete \
            --cache-control "public, max-age=31536000" \
            --exclude "*.html"
          
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} \
            --exclude "*" \
            --include "*.html" \
            --cache-control "public, max-age=3600" \
            --delete
      
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
      
      - name: Deployment complete
        run: |
          echo "✅ Deployment successful!"
          echo "Website: https://n8tive.io"
          echo "Note: Cache invalidation may take 5-15 minutes"

